from typing import Any, Dict, List, Optional

from typing_extensions import TypedDict


class ObjectBox(TypedDict):
    """A single detected object, including label, confidence, and bounding box."""

    label: str
    confidence: float
    bbox: List[float]  # x1, y1, x2, y2


class ExecutionInstruction(TypedDict):
    """Execution instruction: code generated by Coding Agent, executed by Execution Agent."""
    
    operator: str  # Operator name, e.g., "yolo_detector", "sql_executor"
    params: Dict[str, Any]  # Operator parameters


class AgentState(TypedDict, total=False):
    """Unified state shared across agents."""

    # Human input
    user_text: Optional[str]
    image_path: Optional[str]

    # Decomposition Agent (intent)
    intent: Optional[str]

    # Coding Agent (generated execution instructions)
    perception_instruction: Optional[ExecutionInstruction]  # Perception call instruction (YOLO detection)
    
    # Execution Agent (perception)
    objects: Optional[List[ObjectBox]]

    # Coding Agent (structured representation)
    sql_statements: Optional[List[str]]
    current_sql: Optional[str]
    current_index: Optional[int]
    executed_sqls: Optional[List[str]]

    # Execution Agent (database queries)
    query_results: Optional[List[str]]

    # Coordination Agent (summary / output)
    filter_results: Optional[List[Dict[str, Any]]]
    summary: Optional[str]
    chat_response: Optional[str]


def get_init_agent_state(user_text: str, image_path: str) -> AgentState:
    """Create initial state for multi-agent pipeline."""

    return AgentState(
        user_text=user_text,
        image_path=image_path,
        intent="",
        perception_instruction=None,
        objects=[],
        sql_statements=[],
        current_sql="",
        current_index=-1,
        executed_sqls=[],
        query_results=[],
        filter_results=[],
        summary="",
        chat_response="",
    )
