from typing import List, Optional, Dict, Any

from typing_extensions import TypedDict


class ObjectBox(TypedDict):
    label: str
    confidence: float
    bbox: List[float]  # x1, y1, x2, y2


class AgentState(TypedDict):
    """The state structure that flows within the Agent graph."""
    user_text: Optional[str]                        # User input
    image_path: Optional[str]                       # Path to the stored image

    intent: Optional[str]                           # Intent: "chat" or "reasoning"

    objects: Optional[List[ObjectBox]]              # Entities detected during the perception stage

    sql_statements: Optional[List[str]]             # All generated SQL statements
    current_sql: Optional[str]                      # Currently processed SQL
    current_index: Optional[int]                    # Index of the currently processed SQL
    executed_sqls: Optional[List[str]]              # Executed SQL statements

    query_results: Optional[List[str]]              # All query results
    filter_results: Optional[List[Dict[str, Any]]]  # Results after filtering out empty entries
    summary: Optional[str]                          # Summary generated by the large language model

    chat_response: Optional[str]                    # Chat response


def get_init_agent_state(user_text: str, image_path: str) -> AgentState:
    state: AgentState = {
        "user_text": user_text,
        "image_path": image_path,

        "intent": "",

        "objects": [],

        "sql_statements": [],
        "current_sql": "",
        "current_index": -1,
        "executed_sqls": [],

        "query_results": [],
        "filter_results": [],
        "summary": "",

        "chat_response": "",
    }
    return state
