"""
Coding Agent

According to the paper: The coding agent provides concrete implementations for each subtask under the guidance of formal representations (such as AST),
generating heterogeneous programming languages (Python, SQL, Prolog, etc.), which can be executed to obtain the desired output.

Responsibilities:
- Select coding operators from operator pool
- Generate execution instructions (perception calls, SQL queries, etc.)
- Encode perception results into executable programs (SQL, Python, etc.)

Interface separation: Coding Agent is only responsible for generating code/instructions, not execution.
"""
from agent.shared.state import AgentState
from operators import OPERATOR_REGISTRY

# Select operators from operator pool
from operators.coding.sql_generator import generate_sql_queries  # Select from operator pool: SQL generation operator
from operators.coding.perception_code_generator import generate_perception_instruction  # Select from operator pool: perception code generation operator


class CodingAgent:
    """
    Coding Agent: Selects coding operators from operator pool, generates execution instructions and executable programs.
    
    According to the paper, the coding agent's responsibilities are:
    - Provide concrete implementations for each subtask under the guidance of formal representations (such as AST)
    - Generate heterogeneous programming languages (Python, SQL, Prolog, etc.)
    - These programs can be executed to obtain the desired output
    
    Interface separation principle:
    - Coding Agent is only responsible for generating code/instructions, not execution
    - Execution Agent is responsible for executing code/instructions generated by Coding Agent
    
    Current operators selected from operator pool:
    - operators.coding.perception_code_generator.generate_perception_instruction (perception code generation operator)
    - operators.coding.sql_generator.generate_sql_queries (SQL generation operator)
    
    Future extensions:
    - Python coding operators
    - Prolog coding operators
    - Coding operators for other heterogeneous programming languages
    """

    def __init__(self):
        # Operator registry (UOP - Unified Operator Pool)
        self.operator_registry = OPERATOR_REGISTRY
        # Operator categories available to current Agent
        self.available_categories = ["coding"]

    def generate_perception_code(self, state: AgentState) -> AgentState:
        """
        Call coding operator: Generate execution instruction for YOLO perception call
        
        Select from operator pool: operators.coding.perception_code_generator.generate_perception_instruction
        
        Interface separation: Coding Agent generates instructions, does not execute. Execution is handled by Execution Agent.
        """
        print("\n================================[PerceptionCodingAgent]=================================\n")
        print("PerceptionCodingAgent called perception code generation function:")
        # Call coding operator from operator pool, generate execution instruction
        instruction = generate_perception_instruction(state)
        print(f"Generated execution instruction - operator: {instruction['operator']}")
        print(f"Generated execution instruction - params: {instruction['params']}")
        new_state = state.copy()
        new_state["perception_instruction"] = instruction  # Store generated instruction in state
        return new_state

    def generate_sql(self, state: AgentState) -> AgentState:
        """
        Call coding operator: Encode perception results as SQL queries
        
        Select from operator pool: operators.coding.sql_generator.generate_sql_queries
        
        Interface separation: Coding Agent generates SQL, does not execute. Execution is handled by Execution Agent.
        """
        print("\n================================[SqlCodingAgent]=================================\n")
        print("SqlCodingAgent called SQL generation function:")
        # Call coding operator from operator pool
        sqls = generate_sql_queries(state["objects"] or [])
        sql_statements = (state["sql_statements"] or []) + sqls
        print(f"Generated {len(sql_statements)} SQL queries based on detected entities:")
        for i, sql in enumerate(sql_statements, 1):
            print(f"[{i}] {sql}")
        new_state = state.copy()  # Create new state, add SQL statements, output state
        new_state["sql_statements"] = sql_statements
        return new_state

